package com.aircontrol;

import android.content.Context;
import android.text.TextUtils;
import android.util.Log;
import org.json.JSONObject;
import java.io.BufferedReader;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileOutputStream;
import java.io.InputStream;
import java.io.InputStreamReader;
import java.net.HttpURLConnection;
import java.net.InetAddress;
import java.net.URI;
import java.net.URLEncoder;
import java.net.URL;
import java.nio.charset.StandardCharsets;
import java.util.Locale;

/** Executes bounded web, memory, Android UI, app-discovery and local-workspace tools for NOVA. */
public final class NovaToolExecutor {
    private static final String TAG="NovaToolExecutor"; private static final int CONNECT_TIMEOUT_MS=8000,READ_TIMEOUT_MS=12000,MAX_RESPONSE_CHARS=30000,MAX_FILE_CHARS=100000,MAX_REDIRECTS=4,MAX_APPS_CHARS=12000;
    private final File workspace; private final NovaMemory memory; private final NovaAppCatalog apps; private final NovaActionEngine actions;
    public NovaToolExecutor(Context context){Context app=context.getApplicationContext();workspace=new File(app.getFilesDir(),"nova-workspace");if(!workspace.exists())workspace.mkdirs();memory=new NovaMemory(app);apps=new NovaAppCatalog(app);actions=new NovaActionEngine(app,new NovaActionEngine.Callback(){public void status(String text){Log.d(TAG,"ACTION STATUS: "+text);}public void reply(String text){Log.d(TAG,"ACTION REPLY: "+text);}});}
    public String execute(String type,String value){if(type==null)return null;try{switch(type.trim().toLowerCase(Locale.ROOT)){
        case "home":case "back":case "recents":case "notifications":case "quick_settings":case "scroll_up":case "scroll_down":case "swipe_left":case "swipe_right":case "open_url":case "open_package":case "open_app":case "settings":return executeAndroid(type.trim().toLowerCase(Locale.ROOT),value);
        case "click_text":return clickText(value); case "click_index":return clickIndex(value); case "click_coordinates":return clickCoordinates(value); case "long_click_text":return longClickText(value); case "type_text":return typeText(value); case "read_screen":return readScreen(); case "verify_screen_contains":return verifyScreenContains(value);
        case "wait":return waitFor(value);
        case "web.open":case "web.fetch":return fetch(value); case "web.search":case "search":return search(value); case "memory.remember":return remember(value); case "memory.recall":return recall(value); case "apps.list":return listApps(value);
        case "files.read":return readFile(value); case "files.write":return writeFile(value,false); case "files.create":return writeFile(value,true); case "code.create":return writeFile(value,true); case "code.modify":return writeFile(value,false);
        case "communication.send_message":case "communication.make_call":return "CONFIRMATION REQUIRED • "+type; default:return null;}}
        catch(Exception e){Log.e(TAG,"TOOL ERROR: "+type,e);return "TOOL ERROR • "+e.getClass().getSimpleName();}}
    private String executeAndroid(String type,String value){boolean ok=actions.execute(type,value);return ok?"ANDROID • DONE • "+type:"ANDROID • FAILED • "+type;}
    private String clickText(String value){GestureAccessibilityService s=GestureAccessibilityService.getInstance();if(s==null)return "ANDROID • ACCESSIBILITY NOT CONNECTED";if(TextUtils.isEmpty(value))return "ANDROID • CLICK TEXT • MISSING TEXT";return actions.clickText(value.trim())?"ANDROID • CLICKED • "+value.trim():"ANDROID • CLICK FAILED • "+value.trim();}
    private String clickIndex(String value){GestureAccessibilityService s=GestureAccessibilityService.getInstance();if(s==null)return "ANDROID • ACCESSIBILITY NOT CONNECTED";try{int i=Integer.parseInt(value==null?"":value.trim());return s.clickVisibleIndex(i)?"ANDROID • CLICKED INDEX • "+i:"ANDROID • CLICK INDEX FAILED • "+i;}catch(NumberFormatException e){return "ANDROID • CLICK INDEX • INVALID INDEX";}}
    private String clickCoordinates(String value){if(TextUtils.isEmpty(value))return "ANDROID • CLICK COORDINATES • MISSING";try{JSONObject o=new JSONObject(value);int x=o.getInt("x"),y=o.getInt("y");return actions.clickCoordinates(x,y)?"ANDROID • CLICKED COORDINATES • "+x+","+y:"ANDROID • CLICK COORDINATES FAILED";}catch(Exception e){return "ANDROID • CLICK COORDINATES • INVALID JSON";}}
    private String longClickText(String value){if(TextUtils.isEmpty(value))return "ANDROID • LONG CLICK • MISSING TEXT";return actions.longClickText(value.trim())?"ANDROID • LONG CLICKED • "+value.trim():"ANDROID • LONG CLICK FAILED • "+value.trim();}
    private String typeText(String value){GestureAccessibilityService s=GestureAccessibilityService.getInstance();if(s==null)return "ANDROID • ACCESSIBILITY NOT CONNECTED";if(TextUtils.isEmpty(value))return "ANDROID • TYPE TEXT • MISSING TEXT";try{JSONObject o=new JSONObject(value);String target=o.optString("target","").trim();String text=o.optString("text","");return actions.typeText(target,text)?"ANDROID • TYPED TEXT":"ANDROID • TYPE FAILED";}catch(Exception ignored){return actions.typeText("",value)?"ANDROID • TYPED TEXT":"ANDROID • TYPE FAILED";}}
    private String waitFor(String value){long ms=500;try{if(value!=null&&!value.trim().isEmpty())ms=Math.max(0,Math.min(5000,Long.parseLong(value.trim())));}catch(NumberFormatException ignored){}try{Thread.sleep(ms);}catch(InterruptedException e){Thread.currentThread().interrupt();return "WAIT • INTERRUPTED";}return "WAIT • DONE • "+ms+"ms";}
    private String readScreen(){GestureAccessibilityService s=GestureAccessibilityService.getInstance();if(s==null)return "ANDROID • ACCESSIBILITY NOT CONNECTED";String snapshot=s.getUiSnapshot();if(snapshot!=null&&!snapshot.trim().isEmpty())return snapshot;String summary=s.getVisibleTextSummary();return summary==null?"":summary;}
    private String verifyScreenContains(String value){String e=value==null?"":value.trim();if(e.isEmpty())return "VERIFY • FAILED • MISSING EXPECTED TEXT";GestureAccessibilityService s=GestureAccessibilityService.getInstance();if(s==null)return "VERIFY • FAILED • ACCESSIBILITY NOT CONNECTED";String snap=s.getUiSnapshot();if(snap==null||snap.trim().isEmpty())snap=s.getVisibleTextSummary();if(snap==null||snap.trim().isEmpty())return "VERIFY • FAILED • EMPTY UI";String n=snap.toLowerCase(Locale.ROOT);for(String term:e.toLowerCase(Locale.ROOT).split("\\s+"))if(!term.isEmpty()&&!n.contains(term))return "VERIFY • FAILED • MISSING • "+e;return "VERIFY • PASSED • "+e;}
    private String remember(String value){if(TextUtils.isEmpty(value))return null;try{JSONObject r=new JSONObject(value);String k=r.optString("key","note").trim(),t=r.optString("value","").trim();if(t.isEmpty())return null;memory.rememberFact(k,t);return "MEMORY • SAVED • "+k;}catch(Exception e){memory.rememberFact("note",value.trim());return "MEMORY • SAVED • note";}}
    private String recall(String value){String r=memory.recall(value==null?"":value.trim());return r==null||r.trim().isEmpty()?"MEMORY • NO MATCHES":r;}
    private String listApps(String value){int max=80;try{if(value!=null&&!value.trim().isEmpty())max=Math.max(1,Math.min(200,Integer.parseInt(value.trim())));}catch(NumberFormatException ignored){}String r=apps.launchableSummary(max);return r.length()>MAX_APPS_CHARS?r.substring(0,MAX_APPS_CHARS):r;}
    private String search(String q)throws Exception{if(TextUtils.isEmpty(q))return null;return fetch("https://html.duckduckgo.com/html/?q="+URLEncoder.encode(q.trim(),"UTF-8"));}
    private String fetch(String raw)throws Exception{if(TextUtils.isEmpty(raw))return null;String current=raw.trim();for(int redirect=0;redirect<=MAX_REDIRECTS;redirect++){URI uri=new URI(current);String scheme=uri.getScheme()==null?"":uri.getScheme().toLowerCase(Locale.ROOT);if(!("https".equals(scheme)||"http".equals(scheme))||uri.getUserInfo()!=null)return null;if(isBlockedHost(uri.getHost()))return "WEB • BLOCKED PRIVATE/LOCAL ADDRESS";HttpURLConnection c=(HttpURLConnection)new URL(current).openConnection();c.setRequestMethod("GET");c.setConnectTimeout(CONNECT_TIMEOUT_MS);c.setReadTimeout(READ_TIMEOUT_MS);c.setInstanceFollowRedirects(false);c.setRequestProperty("User-Agent","NOVA/1.0 Android");c.setRequestProperty("Accept","text/html,text/plain,application/json;q=0.9,*/*;q=0.5");try{int code=c.getResponseCode();if(code>=300&&code<400){String loc=c.getHeaderField("Location");if(TextUtils.isEmpty(loc))return "HTTP "+code;current=new URL(new URL(current),loc).toString();continue;}InputStream stream=code>=400?c.getErrorStream():c.getInputStream();if(stream==null)return "HTTP "+code;String body=readBounded(stream,MAX_RESPONSE_CHARS);if(code<200||code>=300)return "HTTP "+code+"\n"+body;return stripHtml(body);}finally{c.disconnect();}}return "WEB • TOO MANY REDIRECTS";}
    private boolean isBlockedHost(String host)throws Exception{if(TextUtils.isEmpty(host))return true;String l=host.toLowerCase(Locale.ROOT);if("localhost".equals(l)||l.endsWith(".localhost")||l.endsWith(".local"))return true;for(InetAddress a:InetAddress.getAllByName(host))if(a.isLoopbackAddress()||a.isAnyLocalAddress()||a.isLinkLocalAddress()||a.isSiteLocalAddress()||isPrivateIpv4(a.getHostAddress()))return true;return false;}
    private boolean isPrivateIpv4(String ip){if(ip==null||ip.indexOf(':')>=0)return false;String[] p=ip.split("\\.");if(p.length!=4)return false;try{int a=Integer.parseInt(p[0]),b=Integer.parseInt(p[1]);return a==10||a==127||(a==172&&b>=16&&b<=31)||(a==192&&b==168)||(a==169&&b==254);}catch(NumberFormatException e){return true;}}
    private String readFile(String value)throws Exception{String p=parsePath(value);if(p==null)return null;File f=resolve(p);if(!f.isFile())return null;try(FileInputStream in=new FileInputStream(f)){return readBounded(in,MAX_FILE_CHARS);}}
    private String writeFile(String value,boolean createOnly)throws Exception{if(TextUtils.isEmpty(value))return null;JSONObject r=new JSONObject(value);String p=r.optString("path","").trim(),content=r.optString("content","");if(p.isEmpty()||content.length()>MAX_FILE_CHARS)return null;File f=resolve(p);if(createOnly&&f.exists())return null;File parent=f.getParentFile();if(parent!=null&&!parent.exists()&&!parent.mkdirs())return null;try(FileOutputStream out=new FileOutputStream(f,false)){out.write(content.getBytes(StandardCharsets.UTF_8));}return "FILE • "+(createOnly?"CREATED":"WRITTEN")+" • "+p;}
    private String parsePath(String value){if(TextUtils.isEmpty(value))return null;String t=value.trim();if(t.startsWith("{"))try{return new JSONObject(t).optString("path","").trim();}catch(Exception ignored){return null;}return t;}
    private File resolve(String path)throws Exception{if(TextUtils.isEmpty(path))throw new SecurityException("empty path");File f=new File(workspace,path),root=workspace.getCanonicalFile();String c=f.getCanonicalPath(),r=root.getCanonicalPath()+File.separator;if(!c.startsWith(r))throw new SecurityException("path outside workspace");return new File(c);}
    private String readBounded(InputStream stream,int limit)throws Exception{StringBuilder out=new StringBuilder();try(BufferedReader r=new BufferedReader(new InputStreamReader(stream,StandardCharsets.UTF_8))){char[] b=new char[2048];int total=0,n;while((n=r.read(b))!=-1){int remain=limit-total;if(remain<=0)break;int take=Math.min(n,remain);out.append(b,0,take);total+=take;if(take<n)break;}}return out.toString();}
    private String stripHtml(String input){if(input==null)return null;String t=input.replaceAll("(?is)<script[^>]*>.*?</script>"," ").replaceAll("(?is)<style[^>]*>.*?</style>"," ").replaceAll("(?is)<[^>]+>"," ").replace("&nbsp;"," ").replace("&amp;","&").replace("&quot;","\"").replace("&#39;", "'").replaceAll("\\s+"," ").trim();return t.length()>MAX_RESPONSE_CHARS?t.substring(0,MAX_RESPONSE_CHARS):t;}
}
