package com.aircontrol;

import android.util.Log;
import org.json.JSONArray;
import org.json.JSONObject;

/** Bounded observe → plan → act → verify → re-plan loop for NOVA. */
public final class NovaAgentLoop {
    private static final String TAG="NovaAgentLoop"; private static final int MAX_ITERATIONS=4,MAX_RETRIES=2;
    public interface Callback{void status(String text);void reply(String text);}
    private final NovaAiClient ai; private final NovaAgentPlanner planner; private final NovaMemory memory; private final NovaTaskStore taskStore; private final Callback callback;
    private boolean running; private String previousPlanFingerprint=""; private int repeatedPlanCount=0; private String activeEndpoint="",activeApiKey="",activeModel="";
    public NovaAgentLoop(NovaAiClient ai,NovaAgentPlanner planner,NovaMemory memory,NovaTaskStore taskStore,Callback callback){this.ai=ai;this.planner=planner;this.memory=memory;this.taskStore=taskStore;this.callback=callback;}
    public synchronized void start(String goal,String endpoint,String apiKey,String model){if(running){callback.reply("I'm still working on the previous task.");return;}running=true;activeEndpoint=endpoint;activeApiKey=apiKey;activeModel=model;previousPlanFingerprint="";repeatedPlanCount=0;planner.clearConfirmation();taskStore.begin(goal);taskStore.appendHistory("TASK STARTED: "+safe(goal));iterate(goal,endpoint,apiKey,model,0);}
    public synchronized boolean resume(){if(running)return false;String goal=taskStore.getGoal();if(goal.isEmpty()||taskStore.isCompleted()||taskStore.state()==NovaTaskStore.State.FAILED||taskStore.hasPendingConfirmation())return false;if(activeEndpoint.isEmpty()){callback.reply("The paused task is saved, but the AI connection is no longer available for this session.");return false;}taskStore.resume();running=true;previousPlanFingerprint="";repeatedPlanCount=0;taskStore.appendHistory("TASK RESUMED");callback.status("AGENT • TASK RESUMED");iterate(goal,activeEndpoint,activeApiKey,activeModel,taskStore.getIteration());return true;}
    public synchronized boolean confirmAndResume(){if(!taskStore.hasPendingConfirmation()||running)return false;String action=taskStore.pendingAction();planner.grantConfirmation();taskStore.clearPendingConfirmation();taskStore.resume();running=true;previousPlanFingerprint="";repeatedPlanCount=0;taskStore.appendHistory("CONFIRMATION GRANTED • "+safe(action));callback.status("AGENT • CONFIRMATION ACCEPTED");iterate(taskStore.getGoal(),activeEndpoint,activeApiKey,activeModel,taskStore.getIteration());return true;}
    public synchronized void cancelPendingConfirmation(){if(!taskStore.hasPendingConfirmation())return;String action=taskStore.pendingAction();taskStore.clearPendingConfirmation();taskStore.appendHistory("CONFIRMATION DECLINED • "+safe(action));taskStore.finish(false);callback.status("AGENT • CONFIRMATION DECLINED");callback.reply("Okay — I did not perform that action.");}
    private void iterate(String goal,String endpoint,String apiKey,String model,int iteration){taskStore.setIteration(iteration);taskStore.setState(NovaTaskStore.State.WORKING);if(iteration>=MAX_ITERATIONS){finish(false,"I stopped after the safe task limit. The task may need another instruction.");return;}
        callback.status("AGENT • OBSERVE → PLAN • "+(iteration+1)+"/"+MAX_ITERATIONS);String screen=planner.currentScreen();String failures=planner.lastFailuresSummary();String previousResult=taskStore.lastResult();String history=taskStore.history();String progress=taskStore.stepProgress();
        try{JSONArray messages=new JSONArray();JSONObject system=new JSONObject();system.put("role","system");system.put("content","You are NOVA's bounded autonomous Android agent. Return JSON only: {\"complete\":false,\"say\":\"short response\",\"goal_expect\":\"OPTIONAL TEXT THAT PROVES THE FINAL GOAL\",\"remaining_goal\":\"WHAT STILL REMAINS\",\"actions\":[{\"type\":\"ACTION\",\"value\":\"VALUE\",\"expect\":\"OPTIONAL EXPECTED UI TEXT\",\"requires\":0}]}. Maximum 8 actions. Do not claim completion unless the user's goal is actually achieved. Use the current structured accessibility UI to select the most relevant visible target; prefer exact text, semantic labels, editable/clickable state and visible bounds over guessing coordinates. Use click_index or coordinates only when the observed UI makes the target unambiguous. After every state-changing action, use an expectation when possible. If an action fails, gather fresh UI evidence and choose a different strategy. Never blindly repeat a failed action. Respect STEP PROGRESS and COMPLETED STEPS and plan only the remaining goal. If complete=true, provide goal_expect whenever the final state can be checked in the UI. Consequential communication actions require confirmation. Registered tools:\n"+planner.toolSummary()+"\nPrevious failures: "+(failures.isEmpty()?"none":failures));messages.put(system);
            JSONObject context=new JSONObject();context.put("role","system");context.put("content","CURRENT SCREEN:\n"+safe(screen)+"\n\nMEMORY:\n"+safe(memory.factsSummary())+"\n\nLAST RESULT:\n"+safe(previousResult)+"\n\nTASK HISTORY:\n"+safe(history)+"\n\nSTEP PROGRESS:\n"+safe(progress)+"\n\nCURRENT STEP:\n"+taskStore.currentStep()+"\n\nCOMPLETED STEPS:\n"+safe(taskStore.completedSteps())+"\n\nFAILED STEPS:\n"+safe(taskStore.failedSteps())+"\n\nREMAINING GOAL:\n"+safe(taskStore.remainingGoal())+"\n\nTASK STATE:\n"+taskStore.state().name()+"\n\nTASK:\n"+safe(goal));messages.put(context);
            JSONObject user=new JSONObject();user.put("role","user");user.put("content",iteration==0?goal:"Continue the same task from the current state. Re-plan only what remains.");messages.put(user);
            ai.chat(endpoint,apiKey,model,messages,new NovaAiClient.Callback(){@Override public void onResult(String response){handlePlan(goal,endpoint,apiKey,model,iteration,response);}@Override public void onError(String message){taskStore.appendHistory("AI ERROR: "+safe(message));finish(false,"My AI core is unavailable while working on that task.");}});
        }catch(Exception e){Log.e(TAG,"LOOP ERROR",e);finish(false,"I couldn't start the agent loop.");}}
    private void handlePlan(String goal,String endpoint,String apiKey,String model,int iteration,String response){try{callback.status("AGENT • PLAN RECEIVED");taskStore.appendHistory("PLAN "+(iteration+1)+": "+compact(response));JSONObject plan=parseObject(response);if(plan==null){retryOrStop(goal,endpoint,apiKey,model,iteration,"PLAN PARSE FAILURE");return;}
        String fp=planFingerprint(plan);if(!fp.isEmpty()&&fp.equals(previousPlanFingerprint)){repeatedPlanCount++;taskStore.appendHistory("REPEATED PLAN; count="+repeatedPlanCount);if(repeatedPlanCount>=2){finish(false,"I stopped because the same plan kept repeating without making progress.");return;}taskStore.incrementRetries();iterate(goal,endpoint,apiKey,model,iteration+1);return;}previousPlanFingerprint=fp;repeatedPlanCount=0;
        boolean parsed=planner.execute(plan.toString());String toolOutput=planner.lastToolOutput();String failureOutput=planner.lastFailuresSummary();String combined=(failureOutput.isEmpty()?"":"FAILURES: "+failureOutput+"\n")+(toolOutput.isEmpty()?"":"TOOL OUTPUT:\n"+toolOutput);taskStore.setLastResult(combined);if(!combined.isEmpty())taskStore.appendHistory("RESULT "+(iteration+1)+": "+compact(combined));
        if(!parsed||!planner.lastExecutionSuccessful()||!failureOutput.isEmpty()){markFailures(failureOutput);if(containsConfirmationFailure(failureOutput)){String action=extractConfirmationAction(failureOutput);taskStore.awaitConfirmation(action);taskStore.appendHistory("TASK PAUSED FOR CONFIRMATION • "+safe(action));running=false;callback.status("AGENT • AWAITING CONFIRMATION");callback.reply("I need your confirmation before I perform: "+safe(action));return;}retryOrStop(goal,endpoint,apiKey,model,iteration,"ACTION FAILURE");return;}
        taskStore.resetRetries();recordProgress(plan);String remaining=plan.optString("remaining_goal","").trim();if(!remaining.isEmpty())taskStore.setRemainingGoal(remaining);boolean complete=plan.optBoolean("complete",false);String goalExpect=plan.optString("goal_expect","").trim();
        if(complete){if(goalExpect.isEmpty()||verifyGoal(goalExpect)){taskStore.markVerified();taskStore.appendHistory("TASK GOAL VERIFIED");finish(true,plan.optString("say","Done — the task was completed and verified.").trim());}else{taskStore.appendHistory("GOAL VERIFICATION FAILED: "+goalExpect);taskStore.incrementRetries();iterate(goal,endpoint,apiKey,model,iteration+1);}return;}
        taskStore.setState(NovaTaskStore.State.WORKING);iterate(goal,endpoint,apiKey,model,iteration+1);
    }catch(Exception e){Log.e(TAG,"PLAN RESULT ERROR",e);retryOrStop(goal,endpoint,apiKey,model,iteration,"PLAN RESULT ERROR");}}
    private boolean containsConfirmationFailure(String failures){return failures!=null&&failures.toLowerCase(java.util.Locale.ROOT).contains("confirmation_required");}
    private String extractConfirmationAction(String failures){if(failures==null)return "consequential action";for(String f:failures.split(", ")){if(f.toLowerCase(java.util.Locale.ROOT).endsWith("_confirmation_required"))return f.substring(0,f.length()-"_confirmation_required".length());}return "consequential action";}
    private boolean verifyGoal(String expected){String screen=planner.currentScreen();if(screen==null||screen.trim().isEmpty())return false;String s=screen.toLowerCase(java.util.Locale.ROOT);for(String t:expected.toLowerCase(java.util.Locale.ROOT).split("\\s+"))if(!t.isEmpty()&&!s.contains(t))return false;taskStore.setLastResult(taskStore.lastResult()+"\nGOAL VERIFY: "+expected);return true;}
    private void recordProgress(JSONObject plan){try{JSONArray a=plan.optJSONArray("actions");if(a==null)return;StringBuilder p=new StringBuilder(taskStore.stepProgress()),done=new StringBuilder(taskStore.completedSteps());int base=taskStore.currentStep();for(int i=0;i<a.length();i++){JSONObject x=a.optJSONObject(i);if(x==null)continue;String type=x.optString("type","none").trim(),value=x.optString("value","").trim();String marker="STEP "+(base+i+1)+" • VERIFIED • "+type+(value.isEmpty()?"":" • "+value);if(p.indexOf(marker)<0){if(p.length()>0)p.append('\n');p.append(marker);}if(done.indexOf(marker)<0){if(done.length()>0)done.append('\n');done.append(marker);}}taskStore.setCurrentStep(base+a.length());taskStore.setStepProgress(p.toString());taskStore.setCompletedSteps(done.toString());}catch(Exception e){Log.w(TAG,"PROGRESS ERROR",e);}}
    private void markFailures(String failures){try{String value="STEP "+(taskStore.currentStep()+1)+" • FAILED • "+(failures==null||failures.isEmpty()?"unknown":failures);String old=taskStore.failedSteps();taskStore.setFailedSteps(old.isEmpty()?value:old+"\n"+value);}catch(Exception ignored){}}
    private void retryOrStop(String goal,String endpoint,String apiKey,String model,int iteration,String reason){int retry=taskStore.incrementRetries();taskStore.appendHistory(reason+"; retry="+retry);if(retry>=MAX_RETRIES)finish(false,"I stopped after the safe retry limit because the task could not be completed reliably.");else{callback.status("AGENT • RE-PLAN "+retry+"/"+MAX_RETRIES);iterate(goal,endpoint,apiKey,model,iteration+1);}}
    private String planFingerprint(JSONObject plan){try{JSONArray a=plan.optJSONArray("actions");if(a==null)return plan.optBoolean("complete",false)?"complete":"";StringBuilder o=new StringBuilder();for(int i=0;i<a.length();i++){JSONObject x=a.optJSONObject(i);if(x==null)continue;o.append(x.optString("type","none").trim().toLowerCase(java.util.Locale.ROOT)).append('|').append(x.optString("value","").trim()).append('|').append(x.optString("expect","").trim()).append('|').append(x.optInt("requires",0)).append(';');}return o.toString();}catch(Exception e){return "";}}
    private synchronized void finish(boolean success,String message){running=false;taskStore.appendHistory(success?"TASK COMPLETE":"TASK STOPPED");taskStore.finish(success);callback.status(success?"AGENT • TASK COMPLETE":"AGENT • TASK STOPPED");if(message!=null&&!message.trim().isEmpty())callback.reply(message);}
    private String safe(String v){return v==null||v.trim().isEmpty()?"None available.":v;} private String compact(String v){if(v==null)return "";String t=v.replaceAll("\\s+"," ").trim();return t.length()>1800?t.substring(0,1800)+"…":t;}
    private JSONObject parseObject(String raw)throws Exception{if(raw==null)return null;String t=raw.trim();if(t.startsWith("```"))t=t.replaceFirst("^```(?:json)?\\s*","").replaceFirst("\\s*```$","").trim();int s=t.indexOf('{'),e=t.lastIndexOf('}');if(s<0||e<=s)return null;return new JSONObject(t.substring(s,e+1));}
    public synchronized void stop(){if(!running){if(taskStore.hasPendingConfirmation()){taskStore.appendHistory("CONFIRMATION WAIT CANCELLED BY USER");taskStore.clearPendingConfirmation();}return;}running=false;taskStore.appendHistory("TASK PAUSED BY USER");taskStore.pause();callback.status("AGENT • PAUSED");callback.reply("Task paused. You can resume it later.");}public synchronized boolean isRunning(){return running;}
}
